import React from 'react';
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import logo from "../public/Logo.png";

const Layout = ({children, title}) => {
    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Link href="/">
            <header className='mb-8'>
            
                <Image 
                    alt="aa"
                    className='ml-auto mr-auto'
                    width={400}
                    height={400}
                    src={logo}
                />
                
            </header>

            </Link>

            <main className="container mx-auto">
                {children}
            </main>

            <footer className="flex justify-center items-center mt-10">
               
            </footer>
            
        </div>
    );

}

export default Layout;